import 'package:flutter/material.dart';
import 'package:sen_material_design/components/tool/popcap/atlas/merge.dart';
import 'package:sen_material_design/components/tool/popcap/atlas/merge_with_resinfo.dart';
import 'package:sen_material_design/components/tool/popcap/atlas/split.dart';
import 'package:sen_material_design/components/tool/popcap/atlas/split_with_resinfo.dart';
import 'package:sen_material_design/components/tool/popcap/newton/decode.dart';
import 'package:sen_material_design/components/tool/popcap/newton/encode.dart';
import 'package:sen_material_design/components/tool/popcap/pam/from_flash.dart';
import 'package:sen_material_design/components/tool/popcap/pam/from_json.dart';
import 'package:sen_material_design/components/tool/popcap/pam/to_flash.dart';
import 'package:sen_material_design/components/tool/popcap/pam/to_json.dart';
import 'package:sen_material_design/components/tool/popcap/resinfo/merge.dart';
import 'package:sen_material_design/components/tool/popcap/resinfo/split.dart';
import 'package:sen_material_design/components/tool/popcap/resource_group/from_resinfo.dart';
import 'package:sen_material_design/components/tool/popcap/resource_group/merge.dart';
import 'package:sen_material_design/components/tool/popcap/resource_group/split.dart';
import 'package:sen_material_design/components/tool/popcap/resource_group/to_resinfo.dart';
import 'package:sen_material_design/components/tool/popcap/rsb/pack.dart';
import 'package:sen_material_design/components/tool/popcap/rsb/unpack.dart';
import 'package:sen_material_design/components/tool/popcap/rsg/pack.dart';
import 'package:sen_material_design/components/tool/popcap/rsg/unpack.dart';
import 'package:sen_material_design/components/tool/popcap/rton/decode.dart';
import 'package:sen_material_design/components/tool/popcap/rton/decrypt.dart';
import 'package:sen_material_design/components/tool/popcap/rton/decrypt_and_decode.dart';
import 'package:sen_material_design/components/tool/popcap/rton/encode.dart';
import 'package:sen_material_design/components/tool/popcap/rton/encode_and_encrypt.dart';
import 'package:sen_material_design/components/tool/popcap/rton/encrypt.dart';
import 'package:sen_material_design/components/tool/popcap/zlib/compress.dart';
import 'package:sen_material_design/components/tool/popcap/zlib/uncompress.dart';
import 'package:sen_material_design/components/tool/wwise/decode.dart';
import 'package:sen_material_design/components/tool/wwise/encode.dart';

Map<String, Widget> materialWidget = const {
  'popcap.resource_group.split': SplitPopCapResourceGroup(),
  'popcap.resource_group.merge': MergePopCapResourceGroup(),
  'popcap.resource_group.to_resinfo': ToResInfo(),
  'popcap.resource_group.from_resinfo': FromResInfo(),
  'popcap.resinfo.split': SplitResInfo(),
  'popcap.resinfo.merge': MergeResInfo(),
  'popcap.zlib.compress': PopCapZlibCompress(),
  'popcap.zlib.uncompress': PopCapZlibUncompress(),
  'popcap.newton.decode': PopCapNewtonDecode(),
  'popcap.newton.encode': PopCapNewtonEncode(),
  'popcap.resource_group.split_atlas': PopCapAtlasSplit(),
  'popcap.resource_group.merge_atlas': PopCapAtlasMerge(),
  'popcap.rsb.unpack': PopCapRSBUnpack(),
  'popcap.rsb.pack': PopCapRSBPack(),
  'popcap.rsg.unpack': PopCapRSGUnpack(),
  'popcap.rsg.pack': PopCapRSGPack(),
  'popcap.animation.decode_to_json': PopCapAnimationConvertToJson(),
  'popcap.animation.encode_from_json': PopCapAnimationConvertFromJson(),
  'popcap.resinfo.split_atlas': SplitWithResInfo(),
  'popcap.resinfo.merge_atlas': MergeWithResInfo(),
  'popcap.rton.decode': PopCapRTONDecode(),
  'popcap.rton.encode': PopCapRTONEncode(),
  'popcap.rton.decrypt': PopCapRTONDecrypt(),
  'popcap.rton.encrypt': PopCapRTONEncrypt(),
  'wwise.soundbank.decode': WWiseSoundBankDecode(),
  'wwise.soundbank.encode': WWiseSoundBankEncode(),
  'popcap.rton.decrypt_and_decode': PopCapRTONDecryptAndDecode(),
  'popcap.rton.encode_and_encrypt': PopCapRTONEncodeAndEncrypt(),
  'popcap.animation.pam_to_flash': PopCapAnimationConvertToFlash(),
  'popcap.animation.pam_from_flash': PopCapAnimationConvertFromFlash(),
};
