# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Sen

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
      packages: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest | win-latest | osx-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish -c Release -r [platform]
